### ISSUE TITLE
这个软件要是可以支持一下Tim就更好啦 期待作者空了更新

### ISSUE THREAD

**Issue by Chen294** [Yiyiyimu/QQ-History-Backup#20]

**Comment by Yiyiyimu** [comment]
Hello @Chen294 Tim 现在有碰到什么问题呢

**Comment by Chen294** [comment]
我采用的是【楼月安卓手机备份文件提取器】（那个知乎回答中提到的从备份文件提取的），很可能是该提取器只能正确提取QQ的而不兼容TIM的。

日志信息
OperationalError('no such table: Friends')Traceback (most recent call last):
  File "QQ_History.py", line 281, in main
  File "QQ_History.py", line 182, in output
  File "QQ_History.py", line 119, in message
  File "QQ_History.py", line 147, in get_friends
  File "QQ_History.py", line 172, in fill_cursors
sqlite3.OperationalError: no such table: Friends

GUI报错
![GUI_RBCUTm8C9e](https://user-images.githubusercontent.com/41291485/125559660-ea566631-dc44-4d5b-810b-c5ff87fcf1e9.png)

**Comment by Yiyiyimu** [comment]
应该手机系统有自己的备份功能，有试过吗
