### ISSUE TITLE
备份之后的com.tencent.mobile.qq没有file/kc文件怎么破

### ISSUE THREAD

**Issue by Sustary** [Yiyiyimu/QQ-History-Backup#29]
[log.txt](https://github.com/Yiyiyimu/QQ-History-Backup/files/7788700/log.txt)

**Comment by Sustary** [comment]
log.txt 里的内容：
OSError('File not found. Please report your directory layout.')Traceback (most recent call last):
  File "QQ_History.py", line 280, in main
  File "QQ_History.py", line 36, in __init__
  File "QQ_History.py", line 207, in get_key
  File "QQ_History.py", line 222, in unify_path
OSError: File not found. Please report your directory layout.

**Comment by Yiyiyimu** [comment]
可以看看kc是在其他文件夹下吗，如果还是没有的话，可以试试[1.41版](https://github.com/Yiyiyimu/QQ-History-Backup/releases/tag/v1.41)
